### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by wooorm** [sva-dsi/2017-fall-course#2]
The following links look dead, but YMMV:

<details>
<summary>Dead Links</summary>

```txt
README.md
http://pixels4food.com/?logodust

bibliography.md
http://geocolor.io/

lectures/charts.md
https://etherpad.mozilla.org/fed-data
https://exversion.com/
http://blog.cartodb.com/map-of-the-week-pulse-plotting/
http://blog.cartodb.com/plotly/
http://geocolor.io/

lectures/colors.md
http://images.runemadsen.com/1440x/itten_exchange2-e18896ea63b2570f24ce868640af63a3.jpg
http://images.runemadsen.com/1440x/itten_example2_removed-3647f5a05e16cedd55f8eef5b89f0407.jpg
http://images.runemadsen.com/1440x/vitaminwater-f707011dbe764deb074e00b39e858c47.jpg
http://images.runemadsen.com/1440x/bad_mono-746f3c1d5f85542436a302e72f3053c5.jpg
http://demos.pebbleroad.com/tapestry/
http://geocolor.io/

lectures/graphs.md
http://thomas-fletcher.com/friendwheel/
http://gexf.net/format/datasets.html
http://tarot-pedia.meteor.com/

lectures/maps.md
http://cdb.io/1Nvepxt
http://cdb.io/1J4MvVW
http://bikestorming.com/
https://publicdata-transit.firebaseio.com/sf-muni
https://gist.github.com/ohasselblad/4c6b8dc877dc6c870322
https://etherpad.mozilla.org/fed-data
http://docs.cartodb.com/cartodb-editor.html#supported-file-formats
http://lyzidiamond.com/posts/osgeo-august-meeting/
http://{s}.tile.osm.org/{z}/{x}/{y}.png
https://github.com/auremoser/gdi-webmap/blob/master/libraries.geojson
http://blog.cartodb.com/mapping-the-world-ongoing-demonstrations-in-brazil/
http://docs.cartodb.com/cartodb-platform.html
http://docs.cartodb.com/cartodb-platform/cartodb-js.html
http://docs.cartodb.com/cartodb-platform/maps-api.html
http://docs.cartodb.com/cartodb-platform/sql-api.html
http://docs.cartodb.com/cartodb-platform/import-api.html
http://docs.cartodb.com/cartodb-editor.html#supported-file-formats
http://blog.cartodb.com/synced-tables-create-real-time-maps-from-data-anywhere/
http://docs.cartodb.com/cartodb-editor.html#supported-file-formats
http://cdb.io/1Nvepxt
http://cdb.io/1Nvepxt
http://cdb.io/1J4MvVW
http://cdb.io/1J4MvVW
http://bl.ocks.org/ohasselblad/e5e438b4e83a4c1d12e9
http://bikestorming.com/
http://docs.cartodb.com/tutorials/introduction_torque.html
https://publicdata-transit.firebaseio.com/sf-muni
http://blog.cartodb.com/mapping-the-world-ongoing-demonstrations-in-brazil/
http://bl.ocks.org/namessanti/raw/d5cf706f68b7c6dce9a3/#3
http://docs.cartodb.com/tips-and-tricks.html#charts--graphs
http://blog.cartodb.com/map-of-the-week-pulse-plotting/
http://blog.cartodb.com/plotly/
https://etherpad.mozilla.org/fed-data
http://academy.cartodb.com
http://academy.cartodb.com/courses/03-cartodbjs-ground-up/lesson-3.html
http://academy.cartodb.com/courses/04-sql-postgis.html
http://docs.cartodb.com/tutorials.html
http://docs.cartodb.com/cartodb-editor.html
http://docs.cartodb.com/cartodb-platform.html
http://cartodb.com/gallery/
http://geocolor.io/

syllabus.md
https://github.github.com/on-demand/intro-to-github/
https://github.github.com/on-demand/intro-to-github/
http://visdown.amitkaps.com/
https://braid.io/tile/guantanamo-bay-detainees#all
https://etherpad.mozilla.org/fed-data
https://auremoser.github.io/web-intro-js
http://visdown.amitkaps.com/
http://frnsys.com/talks/sva/
https://bl.ocks.org/ohasselblad
https://gist.github.com/ohasselblad/a21a6d59d9b6525d182bcb4aa9d07843
http://opennews.kzhu.io/map-disputes/
http://bl.ocks.org/ohasselblad/e5e438b4e83a4c1d12e9
http://www.theawl.com/2015/08/weirdly-its-almost-the-same-color-as-money
http://design.sunlightlabs.com/projects/Sunlight-StyleGuide-DataViz.pdf
```

</details>

**Comment by auremoser** [comment]
Thank you @wooorm !

**Comment by auremoser** [comment]
Corrected links with `[x]`

* [x] README.md
* [x] http://pixels4food.com/?logodust

* [x] bibliography.md
* [x] ~~http://geocolor.io/~~

* [x] lectures/charts.md
* [x] https://etherpad.mozilla.org/fed-data
* [x] ~~https://exversion.com/~~
* [x] http://blog.cartodb.com/map-of-the-week-pulse-plotting/
* [x] http://blog.cartodb.com/plotly/
* [x] ~~http://geocolor.io/~~

* [x] lectures/colors.md
* [x] http://images.runemadsen.com/1440x/itten_exchange2-e18896ea63b2570f24ce868640af63a3.jpg
* [x] http://images.runemadsen.com/1440x/itten_example2_removed-3647f5a05e16cedd55f8eef5b89f0407.jpg
* [x] http://images.runemadsen.com/1440x/vitaminwater-f707011dbe764deb074e00b39e858c47.jpg
* [x] http://images.runemadsen.com/1440x/bad_mono-746f3c1d5f85542436a302e72f3053c5.jpg
* [x] http://demos.pebbleroad.com/tapestry/
* [x] http://geocolor.io/

* [x] lectures/graphs.md
* [x] http://thomas-fletcher.com/friendwheel/
* [x] http://gexf.net/format/datasets.html
* [x] http://tarot-pedia.meteor.com/
 
* [x] lectures/maps.md
* [x] http://cdb.io/1Nvepxt
* [x] http://cdb.io/1J4MvVW
* [x] http://bikestorming.com/
* [x] https://publicdata-transit.firebaseio.com/sf-muni
* [x] https://gist.github.com/ohasselblad/4c6b8dc877dc6c870322
* [x] https://etherpad.mozilla.org/fed-data
* [x] http://docs.cartodb.com/cartodb-editor.html#supported-file-formats
* [x] http://lyzidiamond.com/posts/osgeo-august-meeting/
* [x] http://{s}.tile.osm.org/{z}/{x}/{y}.png
* [x] https://github.com/auremoser/gdi-webmap/blob/master/libraries.geojson
* [x] http://blog.cartodb.com/mapping-the-world-ongoing-demonstrations-in-brazil/
* [x] http://docs.cartodb.com/cartodb-platform.html
* [x] http://docs.cartodb.com/cartodb-platform/cartodb-js.html
* [x] http://docs.cartodb.com/cartodb-platform/maps-api.html
* [x] http://docs.cartodb.com/cartodb-platform/sql-api.html
* [x] http://docs.cartodb.com/cartodb-platform/import-api.html
* [x] http://docs.cartodb.com/cartodb-editor.html#supported-file-formats
* [x] http://blog.cartodb.com/synced-tables-create-real-time-maps-from-data-anywhere/
* [s] http://docs.cartodb.com/cartodb-editor.html#supported-file-formats
* [x] http://cdb.io/1Nvepxt
* [x] http://cdb.io/1Nvepxt
* [x] http://cdb.io/1J4MvVW
* [x] http://cdb.io/1J4MvVW
* [x] http://bl.ocks.org/ohasselblad/e5e438b4e83a4c1d12e9
* [x] http://bikestorming.com/
* [x] http://docs.cartodb.com/tutorials/introduction_torque.html
* [x] https://publicdata-transit.firebaseio.com/sf-muni
* [x] http://blog.cartodb.com/mapping-the-world-ongoing-demonstrations-in-brazil/
* [x] http://bl.ocks.org/namessanti/raw/d5cf706f68b7c6dce9a3/#3
* [x] http://docs.cartodb.com/tips-and-tricks.html#charts--graphs
* [x] http://blog.cartodb.com/map-of-the-week-pulse-plotting/
* [x] http://blog.cartodb.com/plotly/
* [x] https://etherpad.mozilla.org/fed-data
* [x] http://academy.cartodb.com
* [x] http://academy.cartodb.com/courses/03-cartodbjs-ground-up/lesson-3.html
* [x] http://academy.cartodb.com/courses/04-sql-postgis.html
* [x] http://docs.cartodb.com/tutorials.html
* [x] http://docs.cartodb.com/cartodb-editor.html
* [s] http://docs.cartodb.com/cartodb-platform.html
* [x] http://cartodb.com/gallery/
* [x] http://geocolor.io/

* [x] syllabus.md
* [x] https://github.github.com/on-demand/intro-to-github/
* [x] https://github.github.com/on-demand/intro-to-github/
* [x] http://visdown.amitkaps.com/
* [x] https://braid.io/tile/guantanamo-bay-detainees#all
* [x] https://etherpad.mozilla.org/fed-data
* [x] https://auremoser.github.io/web-intro-js
* [x] http://visdown.amitkaps.com/
* [x] http://frnsys.com/talks/sva/
* [x] https://bl.ocks.org/ohasselblad
* [x] https://gist.github.com/ohasselblad/a21a6d59d9b6525d182bcb4aa9d07843
* [x] http://opennews.kzhu.io/map-disputes/
* [x] http://bl.ocks.org/ohasselblad/e5e438b4e83a4c1d12e9
* [x] http://www.theawl.com/2015/08/weirdly-its-almost-the-same-color-as-money
* [x] http://design.sunlightlabs.com/projects/Sunlight-StyleGuide-DataViz.pdf
